#!/usr/bin/env bash
# Recreates the pieces stow cannot manage (absolute symlinks pointing outside
# the stow tree). Safe to re-run.
set -euo pipefail

# zsh-256color: HyDE hardcodes this plugin into its oh-my-zsh plugin list, but
# ZSH=/usr/share/oh-my-zsh while the plugin only exists under ~/.oh-my-zsh.
# A dedicated ZSH_CUSTOM holding just that plugin avoids shadowing the system
# copies of zsh-autosuggestions / zsh-syntax-highlighting.
if [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-256color" ]; then
    mkdir -p "$HOME/.config/zsh/omz-custom/plugins"
    ln -sfn "$HOME/.oh-my-zsh/custom/plugins/zsh-256color" \
            "$HOME/.config/zsh/omz-custom/plugins/zsh-256color"
    echo "ok   zsh-256color linked"
else
    echo "SKIP zsh-256color: ~/.oh-my-zsh/custom/plugins/zsh-256color not found"
fi

# wallbash vim colorscheme: generated by HyDE from the current wallpaper into
# ~/.config/vim/colors/, then exposed to nvim via its own colors/ dir.
mkdir -p "$HOME/.config/vim/colors" "$HOME/.config/nvim/colors"
ln -sfn "$HOME/.config/vim/colors/wallbash.vim" \
        "$HOME/.config/nvim/colors/wallbash.vim"
echo "ok   nvim wallbash colorscheme linked"
echo
echo "Now run: hyde-shell reload   (regenerates wallbash output incl. wallbash.vim)"
