#!/usr/bin/env bash
# Rebuild this machine from a fresh Arch install.
#
# Run the steps in order. It is deliberately NOT one blind command: HyDE's own
# installer is interactive and reboots expectations, so you want to be present.
#
#   ./install.sh packages   # yay + repo/AUR packages from the manifests
#   ./install.sh hyde       # clone + run the HyDE installer
#   ./install.sh dotfiles   # stow this repo over HyDE's defaults + bootstrap
#   ./install.sh services   # enable the systemd units that were enabled here
#   ./install.sh extras     # npm globals, go bins, conda env
#   ./install.sh tools      # oh-my-zsh, nvim plugins, Mason tools
#
set -euo pipefail
cd "$(dirname "$0")"
HYDE_COMMIT="51b6cbf"   # the HyDE revision this config was built against

# 19 of the explicitly-installed packages (brave-bin, zen-browser-bin,
# google-chrome, anaconda ...) come from chaotic-aur, a third-party repo. On a
# fresh Arch install it is not configured and those installs fail -- see
# packages/requires-chaotic-aur.txt for the list.
step_chaotic() {
  grep -q "chaotic-aur" /etc/pacman.conf && { echo "chaotic-aur already configured"; return; }
  sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
  sudo pacman-key --lsign-key 3056513887B78AEB
  sudo pacman -U --noconfirm \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' \
    'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
  printf '\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n' | sudo tee -a /etc/pacman.conf
  sudo pacman -Sy
}

step_packages() {
  step_chaotic
  command -v yay >/dev/null || {
    sudo pacman -S --needed --noconfirm git base-devel
    tmp=$(mktemp -d); git clone https://aur.archlinux.org/yay.git "$tmp/yay"
    (cd "$tmp/yay" && makepkg -si --noconfirm); rm -rf "$tmp"
  }
  sudo pacman -S --needed --noconfirm - < packages/pacman-native.txt
  yay -S --needed --noconfirm - < packages/pacman-aur.txt
}

step_hyde() {
  [ -d "$HOME/HyDE" ] || git clone https://github.com/HyDE-Project/HyDE "$HOME/HyDE"
  cd "$HOME/HyDE"
  git checkout "$HYDE_COMMIT" 2>/dev/null || echo "note: pinned commit unavailable, using default branch"
  cd Scripts 2>/dev/null || cd "$HOME/HyDE"
  echo ">> run HyDE's installer now (interactive):  ./install.sh"
  echo ">> then re-run:  $OLDPWD/install.sh dotfiles"
}

step_dotfiles() {
  command -v stow >/dev/null || sudo pacman -S --needed --noconfirm stow
  # HyDE ships its own copies of these files; --adopt pulls whatever is on disk
  # into the repo and symlinks it, so check `git diff` afterwards and `git
  # checkout .` to keep THIS repo's version (which is almost always what you want).
  stow --adopt -t "$HOME" hypr waybar kitty zsh tmux starship hyde nvim bin
  echo ">> review: git -C $(pwd) diff     (then: git checkout . to keep the repo's version)"
  ./bootstrap.sh
}

step_services() {
  while read -r u; do [ -n "$u" ] && sudo systemctl enable "$u" || true; done < packages/services-system.txt
  while read -r u; do [ -n "$u" ] && systemctl --user enable "$u" || true; done < packages/services-user.txt
}

# Everything installed outside pacman.
step_extras() {
  # npm globals (gemini-cli, vercel, pnpm, yarn, devcontainers ...)
  command -v npm >/dev/null && xargs -r npm install -g < packages/npm-global.txt
  # go binaries
  command -v go >/dev/null && while read -r b; do
    [ "$b" = "kind" ] && go install sigs.k8s.io/kind@latest
  done < packages/go-bin.txt
  # conda env (the `anaconda` package restores base; this env is yours)
  [ -f packages/conda-backend-env.yml ] && command -v conda >/dev/null && \
    conda env create -f packages/conda-backend-env.yml 2>/dev/null || true
  cat <<'NOTE'

Not automated, reinstall by hand if you still want them:
  - /opt/containerd      installed manually, outside pacman
  - AppImages            ~/Applications/Pencil-*.AppImage, Cursor-*.AppImage
  - ~/.local/bin shims   regenerated by the anaconda package + pip installs
NOTE
}

step_tools() {
  [ -d "$HOME/.oh-my-zsh" ] || git clone https://github.com/ohmyzsh/ohmyzsh "$HOME/.oh-my-zsh"
  # zsh-256color is hardcoded into HyDE's plugin list; bootstrap.sh links it in
  [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-256color" ] || \
    git clone https://github.com/chrissicool/zsh-256color \
      "$HOME/.oh-my-zsh/custom/plugins/zsh-256color"
  ./bootstrap.sh
  # lazy.nvim restores the exact plugin revisions from lazy-lock.json
  nvim --headless "+Lazy! restore" +qa
  # Mason tools are NOT tracked; reinstall the ones this config expects
  nvim --headless -c 'MasonInstall yamllint ansible-lint gitlint curlylint autotools-language-server tailwindcss-language-server' -c 'sleep 60' -c 'qa!' || true
  hyde-shell reload || true
}

case "${1:-}" in
  packages) step_packages ;;
  hyde)     step_hyde ;;
  dotfiles) step_dotfiles ;;
  services) step_services ;;
  extras)   step_extras ;;
  tools)    step_tools ;;
  *) sed -n '2,14p' "$0"; exit 1 ;;
esac
